version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    tty: true
    restart: always
    # ports:
    #   - "127.0.0.1:8081:8080"
    volumes:
      - ../:/workspace

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    tty: true
    restart: always
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    image: quay.io/prometheus/prometheus:v2.48.1
    volumes:
      - ./prometheus.yml:/etc/config/prometheus.yml
    ports:
      - "9090:9090"
    command:
        - --storage.tsdb.retention.time=15d
        - --config.file=/etc/config/prometheus.yml
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --enable-feature=exemplar-storage
        - --enable-feature=otlp-write-receiver
