version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    tty: true
    restart: always
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ../:/workspace
    networks:
      - otel-net

  collector:
    image: otel/opentelemetry-collector:latest
    tty: true
    restart: always
    ports:
      - 127.0.0.1:4317:4317
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - otel-net

networks:
  otel-net: