version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    tty: true
    restart: always
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ../:/workspace

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    tty: true
    restart: always
    ports:
      - 127.0.0.1:4317:4317
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
