receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317

exporters:
  debug:
    verbosity: detailed
processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
