receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317

exporters:
  debug:
    verbosity: detailed
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, zipkin, otlp/jaeger]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
