global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
scrape_configs:
- honor_labels: true
  job_name: opentelemetry-community-demo
  kubernetes_sd_configs:
  - namespaces:
      own_namespace: true
    role: pod
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_pod_annotation_opentelemetry_community_demo
